package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildFeatures.perfmon
import jetbrains.buildServer.configs.kotlin.buildSteps.maven
import jetbrains.buildServer.configs.kotlin.buildSteps.sshExec
import jetbrains.buildServer.configs.kotlin.matrix
import jetbrains.buildServer.configs.kotlin.triggers.vcs
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    expectTemplates()
    templates = arrayListOf(RelativeId("Tw87232"))

    check(artifactRules == "**/*.jar") {
        "Unexpected option value: artifactRules = $artifactRules"
    }
    artifactRules = ""

    vcs {
        remove(DslContext.settingsRoot.id!!)
    }

    expectSteps {
        sshExec {
            id = "ssh_exec_runner"
            enabled = false
            commands = """
                pwd 
                ./script.bat
            """.trimIndent()
            targetUrl = "10.128.93.139"
            authMethod = uploadedKey {
                username = "Administrator"
                passphrase = "credentialsJSON:57da657d-67c5-4f44-a37d-71887366ca3b"
                key = "ollven_windows.pem"
            }
        }
        maven {
            goals = "clean package"
            runnerArgs = "-Dmaven.test.failure.ignore=true"
            jdkHome = "%env.JDK_11%"
            coverageEngine = jacoco {
                classLocations = "+:build/main/**/*"
                jacocoVersion = "%teamcity.tool.jacoco.0.8.2%"
            }
            param("teamcity.coverage.idea.includePatterns", "de.ollven.*")
        }
        step {
            name = "sonar"
            id = "sonar"
            type = "sonar-plugin"
            enabled = false
            param("target.jdk.home", "%env.JDK_17_0%")
            param("teamcity.tool.sonarquberunner", "%teamcity.tool.sonar-qube-scanner.4.2.0.1873-scanner%")
            param("additionalParameters", "-X")
            param("sonarServer", "d84ee010-c3e1-488f-9f29-60a9af1b11ad")
        }
    }
    steps {
        items.removeAt(1)
        check(stepsOrder == arrayListOf<String>()) {
            "Unexpected build steps order: $stepsOrder"
        }
        stepsOrder = arrayListOf("ssh_exec_runner", "RUNNER_1", "sonar")
    }

    triggers {
        remove {
            vcs {
                id = "TRIGGER_1"
                branchFilter = "+:*"
            }
        }
    }

    features {
        remove {
            perfmon {
                id = "BUILD_EXT_1"
            }
        }
        remove {
            matrix {
                id = "BUILD_EXT_4"
                os = listOf(
                    value("Mac OS"),
                    value("Linux")
                )
                param("newParameter", listOf(
                    value("Sn"),
                    value("SomeKindOfLongName"),
                    value("hedlwehkfhkhferkjfhrehfrekhfkreherkfhklerfhkewrhfgjlkehkerhkerhkferhkferhkfhrekfhrekfhreklhfkerfhkerhfkerhfkhjgjlljljhgjgjgjgjhghjhgjhgjhgjgjkgjhgjhgjgjgjgjghjgjgjgjhgjgjgjgjbjhbbjbjhbjgjhbgjkhgjhgkjgjkghjgjhgjkhljhlkjhjlkhjlhljhjkgkhghjhjgjlgljkfldkjfdkfdlkjkvfgd"),
                    value("Value2"),
                    value("Value3"),
                    value("Value4"),
                    value("Value5")
                ))
            }
        }
    }
}
