package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.amazonEC2CloudProfile
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        remove {
            amazonEC2CloudProfile {
                id = "amazon-3"
                name = "Tests Profile"
                terminateIdleMinutes = 30
                region = AmazonEC2CloudProfile.Regions.EU_WEST_DUBLIN
                authType = accessKey {
                    keyId = "credentialsJSON:253da1b9-5eba-438c-9825-64f7503af886"
                    secretKey = "credentialsJSON:5eb86222-6fe6-4757-99f0-d5b683d9dc2f"
                }
            }
        }
    }
}
